### ISSUE TITLE
Questions about design

### ISSUE THREAD

**Issue by greenpdx** [OUISRC/muro#3]
After a day of working with muro, I have some issues.
1) Why do you "window.location.reload (true)" with every route?
2) At the top of every page you have a nav component, Why don't you have the new pages inside the "nav bar" page?
3) with every page load, a websocket connection is attempted. I can not find the code to do that, why is it doing that?
4) there are axios calls all over the code.  Why do you not have a single function for RPC calls?
5) look at github.com/greenpdx/jrpc, jrpc_vue and jsonrpc_diesel. I use paritytech/jsonrpc as my server.

I think this is a great idea and a perfect blend of two technologies. I just want to understand it and make it better.

**Comment by krircc** [comment]
@greenpdx you are right, my code isn't very well and some choice too, I begin the project in order to become familiar with actix-web, I  also implement other functions mske it like 'Rrddit' clone, later i don't have enought time, some code isn't commit and push.
But you can do better, I find actix-web 0.6 is more cool also and diesel 1.2

**Comment by greenpdx** [comment]
Can you add me to the dev list? 
https://github.com/greenpdx/jrpc, https://github.com/greenpdx/jsonrpc_diesel, https://github.com/greenpdx/jrpc_vue

also check out https://taxnvote.org for my 3D vue work.

**Comment by krircc** [comment]
@greenpdx I Invited you to join this organization and then you hane the write competence

**Comment by krircc** [comment]
@greenpdx now the code updated
